all:
	latex graphics
	bibtex graphics
	latex graphics
	latex graphics
	dvips graphics
	ps2pdf graphics.ps

clean:
	rm -f *.blg
	rm -f *.bbl
	rm -f *.log
	rm -f *.aux
	rm -f *.dvi
	rm -f *.ps
	rm -f *.pdf